#include "stencil.hpp"

#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_vector.hpp>

#include <cmath>
#include <vector>

#include <sol/sol.hpp>
#include <spdlog/spdlog.h>

using Catch::Matchers::Approx;
using namespace ccs;

// Reference 5x7 boundary-block coefficients at epsilon=0.9, generated by
// scripts/stencil_gen/tests/fixtures/gaussian_e4u1_reference.py via
// phs.build_diff_matrix_rbf(n=20, p=2, q=3, epsilon=0.9, kernel='gaussian',
// nu=1, nextra=0)[:5, :7]. Row-major, so entry (i,j) lives at index i*7+j.
static const std::vector<real> REFERENCE_EPS09_COEFFS{
    // row 0
    -1.5021918071125040,
    1.8963135686849035,
    -0.39666953694790119,
    0.33404526985932920,
    -0.55237716805204540,
    0.22087967356821858,
    0.0,
    // row 1
    -0.40268058532377188,
    -0.30676322265508538,
    0.92052541052472903,
    -0.39419104240595404,
    0.26726167047692284,
    -0.084152230616840393,
    0.0,
    // row 2
    0.13384135786548415,
    -0.79286136937374030,
    -0.00030143449321403298,
    0.91965894106724189,
    -0.33617489048730148,
    0.075837395421529744,
    0.0,
    // row 3
    -0.075837395421529022,
    0.33617489048729987,
    -0.91965894106724144,
    0.00030143449321441972,
    0.79286136937374019,
    -0.13384135786548421,
    0.0,
    // row 4: classical E4 centered first-derivative stencil at h=1
    0.0,
    0.0,
    1.0 / 12.0,
    -2.0 / 3.0,
    0.0,
    2.0 / 3.0,
    -1.0 / 12.0,
};

namespace
{
std::optional<stencil> make_gaussian_stencil(real epsilon)
{
    sol::state lua;
    lua.open_libraries(sol::lib::base, sol::lib::math);
    lua["epsilon_val"] = epsilon;
    lua.script(R"(
        simulation = {
            scheme = {
                order = 1,
                type = "gaussian_E4u",
                epsilon = epsilon_val
            }
        }
    )");
    return stencil::from_lua(lua["simulation"]);
}
} // namespace

TEST_CASE("gaussian_E4u_1 construction at epsilon=0.9")
{
    auto st_opt = make_gaussian_stencil(0.9);
    REQUIRE(!!st_opt);

    auto [p, r, t, x] = st_opt->query(bcs::Floating);
    REQUIRE(p == 2);
    REQUIRE(r == 5);
    REQUIRE(t == 7);
    REQUIRE(x == 0);
}

TEST_CASE("gaussian_E4u_1 coefficients match Python reference")
{
    auto st_opt = make_gaussian_stencil(0.9);
    REQUIRE(!!st_opt);
    const auto& st = *st_opt;

    // With h=1.0 and right=false, nbs_floating copies cached_coeffs verbatim.
    std::vector<real> c(5 * 7);
    std::vector<real> ex{};
    auto out = st.nbs(1.0, bcs::Floating, 1.0, false, c, ex);

    REQUIRE(out.size() == 5u * 7u);
    REQUIRE_THAT(c, Approx(REFERENCE_EPS09_COEFFS).margin(1.0e-12));
}

TEST_CASE("gaussian_E4u_1 nbs_floating fills output span")
{
    auto st_opt = make_gaussian_stencil(0.9);
    REQUIRE(!!st_opt);
    const auto& st = *st_opt;

    const real h = 0.1;
    std::vector<real> c(5 * 7);
    std::vector<real> ex{};
    auto out = st.nbs(h, bcs::Floating, 1.0, false, c, ex);

    REQUIRE(out.size() == 5u * 7u);
    for (real v : c) {
        REQUIRE(std::isfinite(v));
    }
    // nbs_floating divides cached_coeffs by h; spot-check the interior row.
    REQUIRE(c[4 * 7 + 2] == Catch::Approx(1.0 / (12.0 * h)).margin(1.0e-12));
    REQUIRE(c[4 * 7 + 3] == Catch::Approx(-2.0 / (3.0 * h)).margin(1.0e-12));
}

TEST_CASE("gaussian_E4u_1 Dirichlet query and nbs at epsilon=0.9")
{
    auto st_opt = make_gaussian_stencil(0.9);
    REQUIRE(!!st_opt);
    const auto& st = *st_opt;

    auto [p, r, t, x] = st.query(bcs::Dirichlet);
    REQUIRE(p == 2);
    REQUIRE(r == 4);
    REQUIRE(t == 7);
    REQUIRE(x == 0);

    // Dirichlet drops the first wall row — expected = REFERENCE_EPS09_COEFFS[7..35].
    std::vector<real> c(4 * 7);
    std::vector<real> ex{};
    auto out = st.nbs(1.0, bcs::Dirichlet, 1.0, false, c, ex);

    REQUIRE(out.size() == 4u * 7u);
    const std::vector<real> expected{REFERENCE_EPS09_COEFFS.begin() + 7,
                                     REFERENCE_EPS09_COEFFS.end()};
    REQUIRE_THAT(c, Approx(expected).margin(1.0e-12));
}

TEST_CASE("gaussian_E4u_1 right=true flips Floating block")
{
    auto st_opt = make_gaussian_stencil(0.9);
    REQUIRE(!!st_opt);
    const auto& st = *st_opt;

    // right=true negates every entry and reverses the block end-to-end:
    // c[i] == -REFERENCE_EPS09_COEFFS[34 - i].
    std::vector<real> c(5 * 7);
    std::vector<real> ex{};
    auto out = st.nbs(1.0, bcs::Floating, 1.0, true, c, ex);

    REQUIRE(out.size() == 5u * 7u);
    std::vector<real> expected(REFERENCE_EPS09_COEFFS.size());
    for (std::size_t i = 0; i < expected.size(); ++i) {
        expected[i] = -REFERENCE_EPS09_COEFFS[expected.size() - 1 - i];
    }
    REQUIRE_THAT(c, Approx(expected).margin(1.0e-12));
}
