#include "stencil.hpp"

#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_vector.hpp>

#include <cmath>
#include <vector>

#include <sol/sol.hpp>
#include <spdlog/spdlog.h>

using Catch::Matchers::Approx;
using namespace ccs;

// Reference 5x7 boundary-block coefficients at epsilon=1.0, generated by
// scripts/stencil_gen/tests/fixtures/multiquadric_e4u1_reference.py via
// phs.build_diff_matrix_rbf(n=20, p=2, q=3, epsilon=1.0, kernel='multiquadric',
// nu=1, nextra=0)[:5, :7]. Row-major, so entry (i,j) lives at index i*7+j.
static const std::vector<real> REFERENCE_EPS1_COEFFS{
    // row 0
    -1.5559291990786261,
    2.0696739898512275,
    -0.5527373019519827,
    0.29945995753484317,
    -0.4397579732255186,
    0.17929052687005645,
    0.0,
    // row 1
    -0.38646063730229613,
    -0.34865620341763504,
    0.925897853360169,
    -0.3211499665517351,
    0.19153437320498407,
    -0.06116541929348679,
    0.0,
    // row 2
    0.11442421882997283,
    -0.7390772067352024,
    -0.02126669469225166,
    0.8540211361882415,
    -0.2600544555087824,
    0.05195300191802216,
    0.0,
    // row 3
    -0.05195300191802103,
    0.2600544555087789,
    -0.8540211361882369,
    0.02126669469224796,
    0.7390772067352043,
    -0.11442421882997321,
    0.0,
    // row 4: classical E4 centered first-derivative stencil at h=1
    0.0,
    0.0,
    1.0 / 12.0,
    -2.0 / 3.0,
    0.0,
    2.0 / 3.0,
    -1.0 / 12.0,
};

namespace
{
std::optional<stencil> make_multiquadric_stencil(real epsilon)
{
    sol::state lua;
    lua.open_libraries(sol::lib::base, sol::lib::math);
    lua["epsilon_val"] = epsilon;
    lua.script(R"(
        simulation = {
            scheme = {
                order = 1,
                type = "multiquadric_E4u",
                epsilon = epsilon_val
            }
        }
    )");
    return stencil::from_lua(lua["simulation"]);
}
} // namespace

TEST_CASE("multiquadric_E4u_1 construction at epsilon=1.0")
{
    auto st_opt = make_multiquadric_stencil(1.0);
    REQUIRE(!!st_opt);

    auto [p, r, t, x] = st_opt->query(bcs::Floating);
    REQUIRE(p == 2);
    REQUIRE(r == 5);
    REQUIRE(t == 7);
    REQUIRE(x == 0);
}

TEST_CASE("multiquadric_E4u_1 coefficients match Python reference")
{
    auto st_opt = make_multiquadric_stencil(1.0);
    REQUIRE(!!st_opt);
    const auto& st = *st_opt;

    // With h=1.0 and right=false, nbs_floating copies cached_coeffs verbatim.
    std::vector<real> c(5 * 7);
    std::vector<real> ex{};
    auto out = st.nbs(1.0, bcs::Floating, 1.0, false, c, ex);

    REQUIRE(out.size() == 5u * 7u);
    REQUIRE_THAT(c, Approx(REFERENCE_EPS1_COEFFS).margin(1.0e-12));
}

TEST_CASE("multiquadric_E4u_1 nbs_floating fills output span")
{
    auto st_opt = make_multiquadric_stencil(1.0);
    REQUIRE(!!st_opt);
    const auto& st = *st_opt;

    const real h = 0.1;
    std::vector<real> c(5 * 7);
    std::vector<real> ex{};
    auto out = st.nbs(h, bcs::Floating, 1.0, false, c, ex);

    REQUIRE(out.size() == 5u * 7u);
    for (real v : c) {
        REQUIRE(std::isfinite(v));
    }
    // nbs_floating divides cached_coeffs by h; spot-check the interior row.
    REQUIRE(c[4 * 7 + 2] == Catch::Approx(1.0 / (12.0 * h)).margin(1.0e-12));
    REQUIRE(c[4 * 7 + 3] == Catch::Approx(-2.0 / (3.0 * h)).margin(1.0e-12));
}

TEST_CASE("multiquadric_E4u_1 Dirichlet query and nbs at epsilon=1.0")
{
    auto st_opt = make_multiquadric_stencil(1.0);
    REQUIRE(!!st_opt);
    const auto& st = *st_opt;

    auto [p, r, t, x] = st.query(bcs::Dirichlet);
    REQUIRE(p == 2);
    REQUIRE(r == 4);
    REQUIRE(t == 7);
    REQUIRE(x == 0);

    // Dirichlet drops the first wall row — expected = REFERENCE_EPS1_COEFFS[7..35].
    std::vector<real> c(4 * 7);
    std::vector<real> ex{};
    auto out = st.nbs(1.0, bcs::Dirichlet, 1.0, false, c, ex);

    REQUIRE(out.size() == 4u * 7u);
    const std::vector<real> expected{REFERENCE_EPS1_COEFFS.begin() + 7,
                                     REFERENCE_EPS1_COEFFS.end()};
    REQUIRE_THAT(c, Approx(expected).margin(1.0e-12));
}

TEST_CASE("multiquadric_E4u_1 right=true flips Floating block")
{
    auto st_opt = make_multiquadric_stencil(1.0);
    REQUIRE(!!st_opt);
    const auto& st = *st_opt;

    // right=true negates every entry and reverses the block end-to-end:
    // c[i] == -REFERENCE_EPS1_COEFFS[34 - i].
    std::vector<real> c(5 * 7);
    std::vector<real> ex{};
    auto out = st.nbs(1.0, bcs::Floating, 1.0, true, c, ex);

    REQUIRE(out.size() == 5u * 7u);
    std::vector<real> expected(REFERENCE_EPS1_COEFFS.size());
    for (std::size_t i = 0; i < expected.size(); ++i) {
        expected[i] = -REFERENCE_EPS1_COEFFS[expected.size() - 1 - i];
    }
    REQUIRE_THAT(c, Approx(expected).margin(1.0e-12));
}
