#include "stencil.hpp"

#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_vector.hpp>

#include <cmath>
#include <vector>

#include <sol/sol.hpp>
#include <spdlog/spdlog.h>

using Catch::Matchers::Approx;
using namespace ccs;

// Reference 5x7 boundary-block coefficients at sigma=3.0, generated by
// scripts/stencil_gen/tests/fixtures/tension_e4u1_reference.py via
// phs.build_diff_matrix_rbf(n=20, p=2, q=3, epsilon=3.0, kernel='tension',
// nu=1, nextra=0)[:5, :7]. Row-major, so entry (i,j) lives at index i*7+j.
static const std::vector<real> REFERENCE_SIGMA3_COEFFS{
    // row 0
    -1.4431447064463627,
    1.6506481665645787,
    -0.00447893512802687,
    0.04099487046023337,
    -0.4554220695628875,
    0.21140267411246508,
    0.0,
    // row 1
    -0.42372453421587697,
    -0.19187913132116252,
    0.6714285341100872,
    -0.12576547224451762,
    0.12338453852280763,
    -0.05344393485133798,
    0.0,
    // row 2
    0.09035352266924158,
    -0.6846969596409104,
    0.00191927853789175,
    0.6988886955393713,
    -0.11651500147498403,
    0.01005046436938984,
    0.0,
    // row 3
    -0.01005046436939022,
    0.11651500147498384,
    -0.6988886955393702,
    -0.00191927853789203,
    0.68469695964091,
    -0.09035352266924142,
    0.0,
    // row 4: classical E4 centered first-derivative stencil at h=1
    0.0,
    0.0,
    1.0 / 12.0,
    -2.0 / 3.0,
    0.0,
    2.0 / 3.0,
    -1.0 / 12.0,
};

namespace
{
std::optional<stencil> make_tension_stencil(real sigma)
{
    sol::state lua;
    lua.open_libraries(sol::lib::base, sol::lib::math);
    lua["sigma_val"] = sigma;
    lua.script(R"(
        simulation = {
            scheme = {
                order = 1,
                type = "tension_E4u",
                sigma = sigma_val
            }
        }
    )");
    return stencil::from_lua(lua["simulation"]);
}
} // namespace

TEST_CASE("tension_E4u_1 construction at sigma=3")
{
    auto st_opt = make_tension_stencil(3.0);
    REQUIRE(!!st_opt);

    auto [p, r, t, x] = st_opt->query(bcs::Floating);
    REQUIRE(p == 2);
    REQUIRE(r == 5);
    REQUIRE(t == 7);
    REQUIRE(x == 0);
}

TEST_CASE("tension_E4u_1 coefficients match Python reference")
{
    auto st_opt = make_tension_stencil(3.0);
    REQUIRE(!!st_opt);
    const auto& st = *st_opt;

    // With h=1.0 and right=false, nbs_floating copies cached_coeffs verbatim.
    std::vector<real> c(5 * 7);
    std::vector<real> ex{};
    auto out = st.nbs(1.0, bcs::Floating, 1.0, false, c, ex);

    REQUIRE(out.size() == 5u * 7u);
    REQUIRE_THAT(c, Approx(REFERENCE_SIGMA3_COEFFS).margin(1.0e-12));
}

TEST_CASE("tension_E4u_1 nbs_floating fills output span")
{
    auto st_opt = make_tension_stencil(3.0);
    REQUIRE(!!st_opt);
    const auto& st = *st_opt;

    const real h = 0.1;
    std::vector<real> c(5 * 7);
    std::vector<real> ex{};
    auto out = st.nbs(h, bcs::Floating, 1.0, false, c, ex);

    REQUIRE(out.size() == 5u * 7u);
    for (real v : c) {
        REQUIRE(std::isfinite(v));
    }
    // nbs_floating divides cached_coeffs by h; spot-check the interior row.
    REQUIRE(c[4 * 7 + 2] == Catch::Approx(1.0 / (12.0 * h)).margin(1.0e-12));
    REQUIRE(c[4 * 7 + 3] == Catch::Approx(-2.0 / (3.0 * h)).margin(1.0e-12));
}

TEST_CASE("tension_E4u_1 Dirichlet query and nbs at sigma=3")
{
    auto st_opt = make_tension_stencil(3.0);
    REQUIRE(!!st_opt);
    const auto& st = *st_opt;

    auto [p, r, t, x] = st.query(bcs::Dirichlet);
    REQUIRE(p == 2);
    REQUIRE(r == 4);
    REQUIRE(t == 7);
    REQUIRE(x == 0);

    // Dirichlet drops the first wall row — expected = REFERENCE_SIGMA3_COEFFS[7..35].
    std::vector<real> c(4 * 7);
    std::vector<real> ex{};
    auto out = st.nbs(1.0, bcs::Dirichlet, 1.0, false, c, ex);

    REQUIRE(out.size() == 4u * 7u);
    const std::vector<real> expected{REFERENCE_SIGMA3_COEFFS.begin() + 7,
                                     REFERENCE_SIGMA3_COEFFS.end()};
    REQUIRE_THAT(c, Approx(expected).margin(1.0e-12));
}

TEST_CASE("tension_E4u_1 right=true flips Floating block")
{
    auto st_opt = make_tension_stencil(3.0);
    REQUIRE(!!st_opt);
    const auto& st = *st_opt;

    // right=true negates every entry and reverses the block end-to-end:
    // c[i] == -REFERENCE_SIGMA3_COEFFS[34 - i].
    std::vector<real> c(5 * 7);
    std::vector<real> ex{};
    auto out = st.nbs(1.0, bcs::Floating, 1.0, true, c, ex);

    REQUIRE(out.size() == 5u * 7u);
    std::vector<real> expected(REFERENCE_SIGMA3_COEFFS.size());
    for (std::size_t i = 0; i < expected.size(); ++i) {
        expected[i] = -REFERENCE_SIGMA3_COEFFS[expected.size() - 1 - i];
    }
    REQUIRE_THAT(c, Approx(expected).margin(1.0e-12));
}
