"""Reference gaussian RBF boundary coefficients for gaussian_E4u_1 at epsilon=0.9.

Generated by:

    from stencil_gen.phs import build_diff_matrix_rbf
    D = build_diff_matrix_rbf(n=20, p=2, q=3, epsilon=0.9,
                              kernel="gaussian", nu=1, nextra=0)
    D[:5, :7]  # boundary block: 5 rows x 7 cols = 35 entries

These values are flattened row-major (r=5, t=7) so that entry (i, j)
lives at index i*7 + j, matching the layout expected by the C++
`cached_coeffs` array in `gaussian_E4u_1.cpp`.

The C++ unit test `t-gaussian_E4u_1` hard-pastes these same 35 doubles
into a `std::array<real, 35>` and asserts each cached_coeffs entry
matches within 1e-12.
"""

from __future__ import annotations

import numpy as np

# Shape (5, 7). Row-major flatten gives a length-35 tuple in the order
# required by gaussian_E4u_1::cached_coeffs[i*7 + j].
REFERENCE_GAUSSIAN_E4U1_EPS09_COEFFS: np.ndarray = np.array(
    [
        [
            -1.5021918071125040,
            1.8963135686849035,
            -0.39666953694790119,
            0.33404526985932920,
            -0.55237716805204540,
            0.22087967356821858,
            0.0,
        ],
        [
            -0.40268058532377188,
            -0.30676322265508538,
            0.92052541052472903,
            -0.39419104240595404,
            0.26726167047692284,
            -0.084152230616840393,
            0.0,
        ],
        [
            0.13384135786548415,
            -0.79286136937374030,
            -0.00030143449321403298,
            0.91965894106724189,
            -0.33617489048730148,
            0.075837395421529744,
            0.0,
        ],
        [
            -0.075837395421529022,
            0.33617489048729987,
            -0.91965894106724144,
            0.00030143449321441972,
            0.79286136937374019,
            -0.13384135786548421,
            0.0,
        ],
        [
            0.0,
            0.0,
            0.08333333333333333,
            -0.6666666666666666,
            0.0,
            0.6666666666666666,
            -0.08333333333333333,
        ],
    ],
    dtype=np.float64,
)

assert REFERENCE_GAUSSIAN_E4U1_EPS09_COEFFS.shape == (5, 7)
