"""Reference multiquadric RBF boundary coefficients for multiquadric_E4u_1 at epsilon=1.0.

Generated by:

    from stencil_gen.phs import build_diff_matrix_rbf
    D = build_diff_matrix_rbf(n=20, p=2, q=3, epsilon=1.0,
                              kernel="multiquadric", nu=1, nextra=0)
    D[:5, :7]  # boundary block: 5 rows x 7 cols = 35 entries

These values are flattened row-major (r=5, t=7) so that entry (i, j)
lives at index i*7 + j, matching the layout expected by the C++
`cached_coeffs` array in `multiquadric_E4u_1.cpp`.

The C++ unit test `t-multiquadric_E4u_1` hard-pastes these same 35 doubles
into a `std::array<real, 35>` and asserts each cached_coeffs entry
matches within 1e-12.
"""

from __future__ import annotations

import numpy as np

# Shape (5, 7). Row-major flatten gives a length-35 tuple in the order
# required by multiquadric_E4u_1::cached_coeffs[i*7 + j].
REFERENCE_MULTIQUADRIC_E4U1_EPS1_COEFFS: np.ndarray = np.array(
    [
        [
            -1.5559291990786261,
            2.0696739898512275,
            -0.5527373019519827,
            0.29945995753484317,
            -0.4397579732255186,
            0.17929052687005645,
            0.0,
        ],
        [
            -0.38646063730229613,
            -0.34865620341763504,
            0.925897853360169,
            -0.3211499665517351,
            0.19153437320498407,
            -0.06116541929348679,
            0.0,
        ],
        [
            0.11442421882997283,
            -0.7390772067352024,
            -0.02126669469225166,
            0.8540211361882415,
            -0.2600544555087824,
            0.05195300191802216,
            0.0,
        ],
        [
            -0.05195300191802103,
            0.2600544555087789,
            -0.8540211361882369,
            0.02126669469224796,
            0.7390772067352043,
            -0.11442421882997321,
            0.0,
        ],
        [
            0.0,
            0.0,
            0.08333333333333333,
            -0.6666666666666666,
            0.0,
            0.6666666666666666,
            -0.08333333333333333,
        ],
    ],
    dtype=np.float64,
)

assert REFERENCE_MULTIQUADRIC_E4U1_EPS1_COEFFS.shape == (5, 7)
