"""Reference tension-spline RBF boundary coefficients for tension_E4u_1 at sigma=3.0.

Generated by:

    from stencil_gen.phs import build_diff_matrix_rbf
    D = build_diff_matrix_rbf(n=20, p=2, q=3, epsilon=3.0,
                              kernel="tension", nu=1, nextra=0)
    D[:5, :7]  # boundary block: 5 rows x 7 cols = 35 entries

These values are flattened row-major (r=5, t=7) so that entry (i, j)
lives at index i*7 + j, matching the layout expected by the C++
`cached_coeffs` array in `tension_E4u_1.cpp`.

The C++ unit test `t-tension_E4u_1` hard-pastes these same 35 doubles
into a `std::array<real, 35>` and asserts each cached_coeffs entry
matches within 1e-12.
"""

from __future__ import annotations

import numpy as np

# Shape (5, 7). Row-major flatten gives a length-35 tuple in the order
# required by tension_E4u_1::cached_coeffs[i*7 + j].
REFERENCE_TENSION_E4U1_SIGMA3_COEFFS: np.ndarray = np.array(
    [
        [
            -1.4431447064463627,
            1.6506481665645787,
            -0.00447893512802687,
            0.04099487046023337,
            -0.4554220695628875,
            0.21140267411246508,
            0.0,
        ],
        [
            -0.42372453421587697,
            -0.19187913132116252,
            0.6714285341100872,
            -0.12576547224451762,
            0.12338453852280763,
            -0.05344393485133798,
            0.0,
        ],
        [
            0.09035352266924158,
            -0.6846969596409104,
            0.00191927853789175,
            0.6988886955393713,
            -0.11651500147498403,
            0.01005046436938984,
            0.0,
        ],
        [
            -0.01005046436939022,
            0.11651500147498384,
            -0.6988886955393702,
            -0.00191927853789203,
            0.68469695964091,
            -0.09035352266924142,
            0.0,
        ],
        [
            0.0,
            0.0,
            0.08333333333333333,
            -0.6666666666666666,
            0.0,
            0.6666666666666666,
            -0.08333333333333333,
        ],
    ],
    dtype=np.float64,
)

assert REFERENCE_TENSION_E4U1_SIGMA3_COEFFS.shape == (5, 7)
